import requests
from bs4 import BeautifulSoup
from flask import redirect, render_template, session
from functools import wraps
import re
import os

def apology(message, code=400):
    """Render message as an apology to user."""

    def escape(s):
        """
        Escape special characters.

        https://github.com/jacebrowning/memegen#special-characters
        """
        for old, new in [
            ("-", "--"),
            (" ", "-"),
            ("_", "__"),
            ("?", "~q"),
            ("%", "~p"),
            ("#", "~h"),
            ("/", "~s"),
            ('"', "''"),
        ]:
            s = s.replace(old, new)
        return s

    return render_template("apology.html", top=code, bottom=escape(message)), code


def login_required(f):
    """
    Decorate routes to require login.

    https://flask.palletsprojects.com/en/latest/patterns/viewdecorators/
    """

    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get("user_id") is None:
            return redirect("/login")
        return f(*args, **kwargs)

    return decorated_function

#thumbnail fetchers generated by Copilot, refined by Jack Hua

def get_youtube_thumbnail(url):
    if "v=" in url:
        video_id = url.split("v=")[1].split("&")[0]
    elif "youtu.be/" in url:
        video_id = url.split("youtu.be/")[1].split("?")[0]
    elif "shorts/" in url:
        video_id = url.split("shorts/")[1].split("?")[0]
    else:
        return None

    return f"https://img.youtube.com/vi/{video_id}/maxresdefault.jpg"


def get_tiktok_thumbnail(url):
    try:
        oembed = requests.get(
            "https://www.tiktok.com/oembed",
            params={"url": url},
            timeout=5
        ).json()
        img_url = oembed.get("thumbnail_url")
        
        if not img_url:
            print("Thumbnail URL not found.")
            return False
        
        # Generate unique filename
        base_name = "filename"
        dir_path = "static/thumbnails"
        if not os.path.exists(dir_path):
            os.makedirs(dir_path)
        existing_files = os.listdir(dir_path)
        numbers = []
        for f in existing_files:
            if f.startswith(base_name):
                rest = f[len(base_name):]
                num_str = ''.join(c for c in rest if c.isdigit())
                if num_str:
                    try:
                        numbers.append(int(num_str))
                    except ValueError:
                        pass
        next_num = max(numbers) + 1 if numbers else 1
        extension = '.jpg'
        filename = f"{base_name}{next_num}{extension}"
        
        # Download the actual image bytes
        img_file = requests.get(img_url).content
        
        # Save to a local file
        file_path = f"{dir_path}/{filename}"
        with open(file_path, 'wb') as file:
            file.write(img_file)
            
        print(f"Successfully saved permanent image as {filename}")
        return file_path
    except Exception as error:
        print(f"Error: {error}")
        return False


def get_instagram_thumbnail(url):
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        }
        # 1. Get the page HTML
        response = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(response.text, "html.parser")
        
        # 2. Find the thumbnail URL in meta tags
        og = soup.find("meta", property="og:image")
        if not og:
            print("Thumbnail URL not found.")
            return False
            
        img_url = og["content"]
        
        # Generate unique filename
        base_name = "filename"
        dir_path = "static/thumbnails"
        if not os.path.exists(dir_path):
            os.makedirs(dir_path)
        existing_files = os.listdir(dir_path)
        numbers = []
        for f in existing_files:
            if f.startswith(base_name):
                rest = f[len(base_name):]
                num_str = ''.join(c for c in rest if c.isdigit())
                if num_str:
                    try:
                        numbers.append(int(num_str))
                    except ValueError:
                        pass
        next_num = max(numbers) + 1 if numbers else 1
        extension = '.jpg'
        filename = f"{base_name}{next_num}{extension}"
        
        # 3. Download the actual image bytes immediately
        img_file = requests.get(img_url).content
        
        # 4. Save to a local file
        file_path = f"{dir_path}/{filename}"
        with open(file_path, 'wb') as file:
            file.write(img_file)
            
        print(f"Successfully saved permanent image as {filename}")
        return file_path
    except Exception as error:
        print(f"Error: {error}")
        return False




def get_youtube_title(url):
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=5)
        soup = BeautifulSoup(response.text, "html.parser")

        meta = soup.find("meta", {"name": "title"})
        if meta and meta.get("content"):
            return meta["content"]
    except Exception:
        pass

    return None

def get_tiktok_title(url):
    try:
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://www.google.com/",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9",
        }

        response = requests.get(url, headers=headers, timeout=5)
        html = response.text

        # Try SIGI_STATE block
        match = re.search(
            r'<script[^>]*id="SIGI_STATE"[^>]*>(.*?)</script>',
            html,
            flags=re.DOTALL
        )

        if match:
            json_text = match.group(1)
            desc_match = re.search(r'"desc"\s*:\s*"([^"]+)"', json_text)
            if desc_match:
                return desc_match.group(1).strip()

        # Fallback: search entire HTML
        desc_match = re.search(r'"desc"\s*:\s*"([^"]+)"', html)
        if desc_match:
            return desc_match.group(1).strip()

        return None

    except Exception:
        return None



def get_instagram_title(url):
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=5)
        soup = BeautifulSoup(response.text, "html.parser")

        meta = soup.find("meta", {"property": "og:description"})
        if not meta or not meta.get("content"):
            return None

        raw = meta["content"]

        # Extract full caption inside quotes (multi-line safe)
        match = re.search(r'"(.+)"', raw, flags=re.DOTALL)
        if match:
            caption = match.group(1).strip()
            return caption

        return raw

    except Exception:
        return None


def shorten_title(title, words=10):
    if not title:
        return "Untitled"
    return " ".join(title.split()[:words])


def extract_urls(text):
    pattern = r'(https?://[^\s]+)'
    return re.findall(pattern, text)




