-- code generated by ChatGPT, refined by Jack Hua

-- Table: videos
CREATE TABLE videos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    link TEXT NOT NULL,
    thumbnail TEXT NOT NULL,
    platform TEXT NOT NULL,
    content_type TEXT NOT NULL,
    mood TEXT,
    notes TEXT,
    tag TEXT,
    user_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
);


-- Table: users
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL);
